// List of all 114 surahs for dropdown selection
export const SURAH_LIST = [
  { id: 1, name: "الفاتحة", transliteration: "Al-Fatihah", translation: "Pembukaan", verses: 7 },
  { id: 2, name: "البقرة", transliteration: "Al-Baqarah", translation: "Sapi Betina", verses: 286 },
  { id: 3, name: "آل عمران", transliteration: "Ali 'Imran", translation: "Keluarga Imran", verses: 200 },
  { id: 4, name: "النساء", transliteration: "An-Nisa", translation: "Wanita", verses: 176 },
  { id: 5, name: "المائدة", transliteration: "Al-Ma'idah", translation: "Hidangan", verses: 120 },
  { id: 6, name: "الأنعام", transliteration: "Al-An'am", translation: "Hewan Ternak", verses: 165 },
  { id: 7, name: "الأعراف", transliteration: "Al-A'raf", translation: "Tempat Tertinggi", verses: 206 },
  { id: 8, name: "الأنفال", transliteration: "Al-Anfal", translation: "Harta Rampasan Perang", verses: 75 },
  { id: 9, name: "التوبة", transliteration: "At-Taubah", translation: "Pengampunan", verses: 129 },
  { id: 10, name: "يونس", transliteration: "Yunus", translation: "Yunus", verses: 109 },
  { id: 11, name: "هود", transliteration: "Hud", translation: "Hud", verses: 123 },
  { id: 12, name: "يوسف", transliteration: "Yusuf", translation: "Yusuf", verses: 111 },
  { id: 13, name: "الرعد", transliteration: "Ar-Ra'd", translation: "Guruh", verses: 43 },
  { id: 14, name: "ابراهيم", transliteration: "Ibrahim", translation: "Ibrahim", verses: 52 },
  { id: 15, name: "الحجر", transliteration: "Al-Hijr", translation: "Hijr", verses: 99 },
  { id: 16, name: "النحل", transliteration: "An-Nahl", translation: "Lebah", verses: 128 },
  { id: 17, name: "الإسراء", transliteration: "Al-Isra", translation: "Perjalanan Malam", verses: 111 },
  { id: 18, name: "الكهف", transliteration: "Al-Kahf", translation: "Gua", verses: 110 },
  { id: 19, name: "مريم", transliteration: "Maryam", translation: "Maryam", verses: 98 },
  { id: 20, name: "طه", transliteration: "Taha", translation: "Taha", verses: 135 },
  { id: 21, name: "الأنبياء", transliteration: "Al-Anbiya", translation: "Para Nabi", verses: 112 },
  { id: 22, name: "الحج", transliteration: "Al-Hajj", translation: "Haji", verses: 78 },
  { id: 23, name: "المؤمنون", transliteration: "Al-Mu'minun", translation: "Orang-orang Mukmin", verses: 118 },
  { id: 24, name: "النور", transliteration: "An-Nur", translation: "Cahaya", verses: 64 },
  { id: 25, name: "الفرقان", transliteration: "Al-Furqan", translation: "Pembeda", verses: 77 },
  { id: 26, name: "الشعراء", transliteration: "Asy-Syu'ara", translation: "Para Penyair", verses: 227 },
  { id: 27, name: "النمل", transliteration: "An-Naml", translation: "Semut", verses: 93 },
  { id: 28, name: "القصص", transliteration: "Al-Qasas", translation: "Kisah-kisah", verses: 88 },
  { id: 29, name: "العنكبوت", transliteration: "Al-'Ankabut", translation: "Laba-laba", verses: 69 },
  { id: 30, name: "الروم", transliteration: "Ar-Rum", translation: "Romawi", verses: 60 },
  { id: 31, name: "لقمان", transliteration: "Luqman", translation: "Luqman", verses: 34 },
  { id: 32, name: "السجدة", transliteration: "As-Sajdah", translation: "Sajdah", verses: 30 },
  { id: 33, name: "الأحزاب", transliteration: "Al-Ahzab", translation: "Golongan-golongan", verses: 73 },
  { id: 34, name: "سبإ", transliteration: "Saba", translation: "Saba", verses: 54 },
  { id: 35, name: "فاطر", transliteration: "Fatir", translation: "Pencipta", verses: 45 },
  { id: 36, name: "يس", transliteration: "Yasin", translation: "Yasin", verses: 83 },
  { id: 37, name: "الصافات", transliteration: "As-Saffat", translation: "Barisan-barisan", verses: 182 },
  { id: 38, name: "ص", transliteration: "Sad", translation: "Sad", verses: 88 },
  { id: 39, name: "الزمر", transliteration: "Az-Zumar", translation: "Rombongan", verses: 75 },
  { id: 40, name: "غافر", transliteration: "Ghafir", translation: "Pengampun", verses: 85 },
  { id: 41, name: "فصلت", transliteration: "Fussilat", translation: "Dijelaskan", verses: 54 },
  { id: 42, name: "الشورى", transliteration: "Asy-Syura", translation: "Musyawarah", verses: 53 },
  { id: 43, name: "الزخرف", transliteration: "Az-Zukhruf", translation: "Perhiasan", verses: 89 },
  { id: 44, name: "الدخان", transliteration: "Ad-Dukhan", translation: "Kabut", verses: 59 },
  { id: 45, name: "الجاثية", transliteration: "Al-Jasiyah", translation: "Berlutut", verses: 37 },
  { id: 46, name: "الأحقاف", transliteration: "Al-Ahqaf", translation: "Bukit Pasir", verses: 35 },
  { id: 47, name: "محمد", transliteration: "Muhammad", translation: "Muhammad", verses: 38 },
  { id: 48, name: "الفتح", transliteration: "Al-Fath", translation: "Kemenangan", verses: 29 },
  { id: 49, name: "الحجرات", transliteration: "Al-Hujurat", translation: "Kamar-kamar", verses: 18 },
  { id: 50, name: "ق", transliteration: "Qaf", translation: "Qaf", verses: 45 },
  { id: 51, name: "الذاريات", transliteration: "Az-Zariyat", translation: "Angin yang Menerbangkan", verses: 60 },
  { id: 52, name: "الطور", transliteration: "At-Tur", translation: "Bukit", verses: 49 },
  { id: 53, name: "النجم", transliteration: "An-Najm", translation: "Bintang", verses: 62 },
  { id: 54, name: "القمر", transliteration: "Al-Qamar", translation: "Bulan", verses: 55 },
  { id: 55, name: "الرحمن", transliteration: "Ar-Rahman", translation: "Yang Maha Pengasih", verses: 78 },
  { id: 56, name: "الواقعة", transliteration: "Al-Waqi'ah", translation: "Hari Kiamat", verses: 96 },
  { id: 57, name: "الحديد", transliteration: "Al-Hadid", translation: "Besi", verses: 29 },
  { id: 58, name: "المجادلة", transliteration: "Al-Mujadilah", translation: "Wanita yang Berdebat", verses: 22 },
  { id: 59, name: "الحشر", transliteration: "Al-Hasyr", translation: "Pengusiran", verses: 24 },
  { id: 60, name: "الممتحنة", transliteration: "Al-Mumtahanah", translation: "Wanita yang Diuji", verses: 13 },
  { id: 61, name: "الصف", transliteration: "As-Saff", translation: "Barisan", verses: 14 },
  { id: 62, name: "الجمعة", transliteration: "Al-Jumu'ah", translation: "Jumat", verses: 11 },
  { id: 63, name: "المنافقون", transliteration: "Al-Munafiqun", translation: "Orang-orang Munafik", verses: 11 },
  { id: 64, name: "التغابن", transliteration: "At-Taghabun", translation: "Hari Dinampakkan Kesalahan", verses: 18 },
  { id: 65, name: "الطلاق", transliteration: "At-Talaq", translation: "Talak", verses: 12 },
  { id: 66, name: "التحريم", transliteration: "At-Tahrim", translation: "Pengharaman", verses: 12 },
  { id: 67, name: "الملك", transliteration: "Al-Mulk", translation: "Kerajaan", verses: 30 },
  { id: 68, name: "القلم", transliteration: "Al-Qalam", translation: "Pena", verses: 52 },
  { id: 69, name: "الحاقة", transliteration: "Al-Haqqah", translation: "Hari Kiamat", verses: 52 },
  { id: 70, name: "المعارج", transliteration: "Al-Ma'arij", translation: "Tempat Naik", verses: 44 },
  { id: 71, name: "نوح", transliteration: "Nuh", translation: "Nuh", verses: 28 },
  { id: 72, name: "الجن", transliteration: "Al-Jinn", translation: "Jin", verses: 28 },
  { id: 73, name: "المزمل", transliteration: "Al-Muzzammil", translation: "Orang yang Berselimut", verses: 20 },
  { id: 74, name: "المدثر", transliteration: "Al-Muddassir", translation: "Orang yang Berkemul", verses: 56 },
  { id: 75, name: "القيامة", transliteration: "Al-Qiyamah", translation: "Hari Kiamat", verses: 40 },
  { id: 76, name: "الانسان", transliteration: "Al-Insan", translation: "Manusia", verses: 31 },
  { id: 77, name: "المرسلات", transliteration: "Al-Mursalat", translation: "Malaikat yang Diutus", verses: 50 },
  { id: 78, name: "النبإ", transliteration: "An-Naba", translation: "Berita Besar", verses: 40 },
  { id: 79, name: "النازعات", transliteration: "An-Nazi'at", translation: "Malaikat yang Mencabut", verses: 46 },
  { id: 80, name: "عبس", transliteration: "Abasa", translation: "Bermuka Masam", verses: 42 },
  { id: 81, name: "التكوير", transliteration: "At-Takwir", translation: "Menggulung", verses: 29 },
  { id: 82, name: "الإنفطار", transliteration: "Al-Infitar", translation: "Terbelah", verses: 19 },
  { id: 83, name: "المطففين", transliteration: "Al-Mutaffifin", translation: "Orang yang Curang", verses: 36 },
  { id: 84, name: "الإنشقاق", transliteration: "Al-Insyiqaq", translation: "Terbelah", verses: 25 },
  { id: 85, name: "البروج", transliteration: "Al-Buruj", translation: "Gugusan Bintang", verses: 22 },
  { id: 86, name: "الطارق", transliteration: "At-Tariq", translation: "Yang Datang di Malam Hari", verses: 17 },
  { id: 87, name: "الأعلى", transliteration: "Al-A'la", translation: "Yang Paling Tinggi", verses: 19 },
  { id: 88, name: "الغاشية", transliteration: "Al-Ghasyiyah", translation: "Hari Pembalasan", verses: 26 },
  { id: 89, name: "الفجر", transliteration: "Al-Fajr", translation: "Fajar", verses: 30 },
  { id: 90, name: "البلد", transliteration: "Al-Balad", translation: "Negeri", verses: 20 },
  { id: 91, name: "الشمس", transliteration: "Asy-Syams", translation: "Matahari", verses: 15 },
  { id: 92, name: "الليل", transliteration: "Al-Lail", translation: "Malam", verses: 21 },
  { id: 93, name: "الضحى", transliteration: "Ad-Duha", translation: "Duha", verses: 11 },
  { id: 94, name: "الشرح", transliteration: "Asy-Syarh", translation: "Kelapangan", verses: 8 },
  { id: 95, name: "التين", transliteration: "At-Tin", translation: "Buah Tin", verses: 8 },
  { id: 96, name: "العلق", transliteration: "Al-Alaq", translation: "Segumpal Darah", verses: 19 },
  { id: 97, name: "القدر", transliteration: "Al-Qadr", translation: "Kemuliaan", verses: 5 },
  { id: 98, name: "البينة", transliteration: "Al-Bayyinah", translation: "Bukti yang Nyata", verses: 8 },
  { id: 99, name: "الزلزلة", transliteration: "Az-Zalzalah", translation: "Guncangan", verses: 8 },
  { id: 100, name: "العاديات", transliteration: "Al-Adiyat", translation: "Kuda yang Berlari Kencang", verses: 11 },
  { id: 101, name: "القارعة", transliteration: "Al-Qari'ah", translation: "Hari Kiamat", verses: 11 },
  { id: 102, name: "التكاثر", transliteration: "At-Takasur", translation: "Bermegah-megahan", verses: 8 },
  { id: 103, name: "العصر", transliteration: "Al-Asr", translation: "Masa", verses: 3 },
  { id: 104, name: "الهمزة", transliteration: "Al-Humazah", translation: "Pengumpat", verses: 9 },
  { id: 105, name: "الفيل", transliteration: "Al-Fil", translation: "Gajah", verses: 5 },
  { id: 106, name: "قريش", transliteration: "Quraisy", translation: "Quraisy", verses: 4 },
  { id: 107, name: "الماعون", transliteration: "Al-Ma'un", translation: "Barang-barang Berguna", verses: 7 },
  { id: 108, name: "الكوثر", transliteration: "Al-Kautsar", translation: "Nikmat yang Berlimpah", verses: 3 },
  { id: 109, name: "الكافرون", transliteration: "Al-Kafirun", translation: "Orang-orang Kafir", verses: 6 },
  { id: 110, name: "النصر", transliteration: "An-Nasr", translation: "Pertolongan", verses: 3 },
  { id: 111, name: "المسد", transliteration: "Al-Masad", translation: "Gejolak Api", verses: 5 },
  { id: 112, name: "الإخلاص", transliteration: "Al-Ikhlas", translation: "Ikhlas", verses: 4 },
  { id: 113, name: "الفلق", transliteration: "Al-Falaq", translation: "Subuh", verses: 5 },
  { id: 114, name: "الناس", transliteration: "An-Nas", translation: "Manusia", verses: 6 },
];
